# 개발용 오버라이드 - docker-compose up 시 자동 적용
version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
      target: development  # 개발용 스테이지 사용
    volumes:
      - ./frontend:/app           # 소스 코드 실시간 반영
      - /app/node_modules         # node_modules는 컨테이너 유지
    environment:
      - WATCHPACK_POLLING=true    # 핫 리로드 최적화
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development      # 개발 모드 명시
      - HOST=0.0.0.0              # 컨테이너 외부 접근 허용
      - PORT=3000                 # Next.js 개발 서버 포트
    command: ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "3000"]  # 컨테이너 외부 접속 허용

  nginx:  # 개발용 nginx 설정 추가
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # 개발용 설정 파일 사용