spring:
  # PostgreSQL Database Configuration for Docker
  datasource:
    url: jdbc:postgresql://postgres:5432/ott_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false
    username: postgres
    password: 1234

  # Redis Configuration for Docker
  data:
    redis:
      host: redis
      port: 6379
      password: 
      database: 0

  # Email Configuration for Docker (same as main config)
  mail:
    host: smtp.naver.com
    port: 587
    username: kgh9806@naver.com
    password: N3K3PHPKJFFR
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: false
            trust: smtp.naver.com
            protocols: TLSv1.2
          starttls:
            enable: true
            required: true
          from: kgh9806@naver.com
        transport:
          protocol: smtp

# Logging for Docker environment
logging:
  level:
    com.ottproject: DEBUG
    org.springframework.security: DEBUG
    org.springframework.mail: DEBUG 