name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            powershell -NoProfile -NonInteractive -Command "Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'; Set-Location -Path 'C:\solo-project\ott-project'; git pull origin main; $pwd='${{ secrets.REGISTRY_PASSWORD }}'; $pwd | docker login -u '${{ secrets.REGISTRY_USER }}' --password-stdin; $envJson='${{ toJSON(secrets.ENV_FILE) }}'; if ($envJson -and $envJson -ne 'null' -and $envJson.Trim() -ne '""') { $envContent = [System.Text.RegularExpressions.Regex]::Unescape($envJson.Trim('"')); Set-Content -Path .env -Value $envContent -NoNewline }; docker compose -f docker-compose.yml -f docker-compose.prod.yml pull app frontend; docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d app frontend --force-recreate --no-deps; Write-Host '--- VERIFY IMAGES ---'; $lb='{'; $rb='}'; $fmt=$lb+'{.Config.Image}'+$rb+' | '+$lb+'{.Image}'+$rb; $appInfo = docker inspect ott-app --format "$fmt"; $feInfo = docker inspect ott-frontend --format "$fmt"; Write-Host ('app:      ' + $appInfo); Write-Host ('frontend: ' + $feInfo); $idx=$lb+'index .RepoDigests 0'+$rb; $hubApp = docker image inspect para98/ott-backend:latest --format "$idx"; $hubFe  = docker image inspect para98/ott-frontend:latest --format "$idx"; Write-Host ('hub app:      ' + $hubApp); Write-Host ('hub frontend: ' + $hubFe); docker compose -f docker-compose.yml -f docker-compose.prod.yml ps"