name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /d "%USERPROFILE%\ott-project"
          git pull origin main
          docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASSWORD }}
          set "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
          docker compose -f ott-project\docker-compose.yml -f ott-project\docker-compose.prod.yml pull
          docker compose -f ott-project\docker-compose.yml -f ott-project\docker-compose.prod.yml up -d --force-recreate --remove-orphans